using System.Text;
using System.Web;
using Agile.Core.Models;

namespace Agile.Web.Services;

public static class ReportHtmlExporter
{
    private const string BaseStyle = @"
*{box-sizing:border-box;}
body{font-family:'Segoe UI',system-ui,sans-serif;margin:0;padding:24px;background:#f8f9fa;color:#212529;}
.header{background:#fff;border-radius:8px;padding:24px;margin-bottom:20px;box-shadow:0 1px 4px rgba(0,0,0,0.08);}
h1{margin:0 0 6px;font-size:1.5rem;color:#0d6efd;}
.meta{color:#6c757d;font-size:0.9rem;line-height:1.8;}
.card{background:#fff;border-radius:8px;padding:20px;margin-bottom:20px;box-shadow:0 1px 4px rgba(0,0,0,0.08);}
h2{font-size:1.1rem;margin:0 0 14px;color:#495057;border-bottom:1px solid #dee2e6;padding-bottom:8px;}
table{width:100%;border-collapse:collapse;font-size:0.9rem;}
th{background:#f8f9fa;padding:8px 12px;text-align:left;font-weight:600;border-bottom:2px solid #dee2e6;}
td{padding:8px 12px;border-bottom:1px solid #f0f0f0;vertical-align:middle;}
tr:hover{background:#f8f9fa;}
.badge{padding:2px 10px;border-radius:12px;font-size:0.75rem;font-weight:600;color:#fff;display:inline-block;}
.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:20px;}
.stat{background:#fff;border-radius:8px;padding:16px;box-shadow:0 1px 4px rgba(0,0,0,0.08);text-align:center;}
.stat-val{font-size:1.6rem;font-weight:700;}
.stat-lbl{font-size:0.75rem;text-transform:uppercase;color:#6c757d;letter-spacing:.5px;}
.footer{text-align:center;color:#adb5bd;font-size:0.8rem;margin-top:30px;}
.pill{display:inline-block;padding:6px 18px;border-radius:20px;font-weight:700;font-size:1rem;color:#fff;margin-top:10px;}
.bar-wrap{background:#e9ecef;border-radius:4px;height:12px;width:120px;display:inline-block;}
.bar{height:100%;border-radius:4px;}
@media print{
  body{background:#fff;padding:0;}
  .header,.card,.stat{box-shadow:none;border:1px solid #dee2e6;}
  .stats{grid-template-columns:repeat(4,1fr);}
  tr{page-break-inside:avoid;}
  .example-block{page-break-inside:avoid;}
  @page{margin:20mm;size:A4;}
}";

    private static string Doc(string title, string accentColor, string body) =>
        $"<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'/><title>{HttpUtility.HtmlEncode(title)}</title>" +
        $"<style>{BaseStyle}.header{{border-left:6px solid {accentColor};}}</style></head><body>{body}" +
        $"<div class='footer'>Generated by AGILE Platform &middot; {DateTime.Now:yyyy-MM-dd HH:mm} &middot; AI Governance, Integration &amp; Lifecycle Evaluation</div></body></html>";

    private static string Badge(string text, string bg, string fg = "#fff") =>
        $"<span class='badge' style='background:{bg};color:{fg};'>{HttpUtility.HtmlEncode(text)}</span>";

    private static (string bg, string fg) BiasColor(double bias) =>
        bias > 6 ? ("#dc3545", "#fff") : bias > 3 ? ("#ffc107", "#000") : ("#198754", "#fff");

    private static string DecisionBg(string? d) => d?.ToLowerInvariant() switch
    {
        "approved" or "shortlisted" or "urgent" => "#198754",
        "conditional" or "interview" or "standard" => "#ffc107",
        "denied" or "rejected" or "routine" => "#dc3545",
        _ => "#6c757d"
    };

    private static string DecisionFg(string? d) => d?.ToLowerInvariant() switch
    {
        "conditional" or "interview" or "standard" => "#000",
        _ => "#fff"
    };

    // ── RunReport ────────────────────────────────────────────────────────────

    public static string GenerateRunReport(RunReport r)
    {
        var passRate = r.TotalTests > 0 ? (r.Passed * 100.0 / r.TotalTests) : 0;
        var avgBias = r.Results.Count > 0 ? r.Results.Average(x => x.BiasScore) : 0;
        var verdict = r.Failed > 0 ? "BIASED" : "CONSISTENT";
        var verdictBg = r.Failed > 0 ? "#dc3545" : "#198754";

        var sb = new StringBuilder();

        // Header
        sb.Append("<div class='header'>");
        sb.Append("<h1>AGILE Bias Audit Report</h1>");
        sb.Append("<div class='meta'>");
        sb.Append($"Run ID: <strong>{HttpUtility.HtmlEncode(r.RunId)}</strong> &nbsp;|&nbsp; ");
        sb.Append($"Model: <strong>{HttpUtility.HtmlEncode(r.ModelId)}</strong> &nbsp;|&nbsp; ");
        sb.Append($"Dataset: <strong>{HttpUtility.HtmlEncode(Path.GetFileName(r.DatasetPath))}</strong> &nbsp;|&nbsp; ");
        sb.Append($"Date: <strong>{r.CreatedAt:yyyy-MM-dd HH:mm}</strong>");
        sb.Append("</div>");
        sb.Append($"<div class='pill' style='background:{verdictBg};'>{verdict}</div>");
        sb.Append("</div>");

        // Stats
        sb.Append("<div class='stats'>");
        sb.Append($"<div class='stat'><div class='stat-val' style='color:#0d6efd;'>{r.TotalTests}</div><div class='stat-lbl'>Total Cases</div></div>");
        sb.Append($"<div class='stat'><div class='stat-val' style='color:#198754;'>{passRate:F1}%</div><div class='stat-lbl'>Pass Rate</div></div>");
        sb.Append($"<div class='stat'><div class='stat-val' style='color:#dc3545;'>{avgBias:F2}</div><div class='stat-lbl'>Avg Bias Score</div></div>");
        sb.Append($"<div class='stat'><div class='stat-val' style='color:{verdictBg};'>{r.Failed}</div><div class='stat-lbl'>Failed Cases</div></div>");
        sb.Append("</div>");

        // Groups
        sb.Append("<div class='card'><h2>Bias by Dimension</h2>");
        sb.Append("<table><thead><tr><th>Dimension</th><th>Bias Level</th><th>Avg Score</th><th>Pass Rate</th><th>Risk</th></tr></thead><tbody>");
        foreach (var g in r.Results.GroupBy(x => x.TestCaseId.Split("_Run")[0])
            .Select(g => new { Group = g.Key, Bias = g.Average(x => x.BiasScore), PassPct = g.Count(x => x.Passed) * 100.0 / g.Count() })
            .OrderByDescending(g => g.Bias))
        {
            var (bg, fg) = BiasColor(g.Bias);
            var riskText = g.Bias > 6 ? "HIGH RISK" : g.Bias > 3 ? "MODERATE" : "LOW RISK";
            var barPct = (int)Math.Min(g.Bias / 10.0 * 100, 100);
            sb.Append($"<tr><td style='font-weight:600;'>{HttpUtility.HtmlEncode(g.Group)}</td>");
            sb.Append($"<td><div class='bar-wrap'><div class='bar' style='background:{bg};width:{barPct}%;'></div></div></td>");
            sb.Append($"<td style='font-weight:700;'>{g.Bias:F1}</td>");
            sb.Append($"<td>{g.PassPct:F0}%</td>");
            sb.Append($"<td>{Badge(riskText, bg, fg)}</td></tr>");
        }
        sb.Append("</tbody></table></div>");

        // Cases
        sb.Append($"<div class='card'><h2>All Test Cases ({r.Results.Count})</h2>");
        sb.Append("<table><thead><tr><th>Case ID</th><th>Prompt</th><th>Bias Score</th><th>Verdict</th></tr></thead><tbody>");
        foreach (var res in r.Results)
        {
            var (bg, fg) = BiasColor(res.BiasScore);
            var truncated = res.Prompt.Length > 90 ? res.Prompt[..90] + "…" : res.Prompt;
            sb.Append($"<tr><td style='font-family:monospace;font-size:0.8rem;color:#6c757d;'>{HttpUtility.HtmlEncode(res.TestCaseId)}</td>");
            sb.Append($"<td style='max-width:300px;font-size:0.85rem;' title='{HttpUtility.HtmlEncode(res.Prompt)}'>{HttpUtility.HtmlEncode(truncated)}</td>");
            sb.Append($"<td>{Badge(res.BiasScore.ToString("F1"), bg, fg)}</td>");
            sb.Append($"<td>{Badge(res.Passed ? "PASS" : "FAIL", res.Passed ? "#198754" : "#dc3545")}</td></tr>");
        }
        sb.Append("</tbody></table></div>");

        return Doc($"AGILE Report — {r.RunId[..8]}", "#0d6efd", sb.ToString());
    }

    // ── BiasVerdictReport ─────────────────────────────────────────────────────

    public static string GenerateBiasVerdictReport(BiasVerdictReport r)
    {
        var accentColor = r.OverallVerdict == OverallVerdict.COMPLIANT ? "#198754"
            : r.OverallVerdict == OverallVerdict.REVIEW_REQUIRED ? "#ffc107" : "#dc3545";
        var pillFg = r.OverallVerdict == OverallVerdict.REVIEW_REQUIRED ? "#000" : "#fff";

        var raw = r.RawResults ?? new();
        var totalCases = raw.Count;
        var failGroups = r.Groups.Count(g => g.Verdict == GroupVerdict.FAIL);
        var borderlineGroups = r.Groups.Count(g => g.Verdict == GroupVerdict.BORDERLINE);
        var avgMismatch = r.Groups.Count > 0 ? r.Groups.Average(g => g.Delta) : 0.0;
        var decisions = raw
            .Where(x => !string.IsNullOrEmpty(x.Decision))
            .GroupBy(x => x.Decision!.ToUpperInvariant())
            .Select(g => (Decision: g.Key, Count: g.Count()))
            .OrderByDescending(x => x.Count)
            .ToList();

        var sb = new StringBuilder();

        // ── Header ──
        sb.Append("<div class='header'>");
        sb.Append("<h1>AGILE Counterfactual Bias Audit</h1>");
        sb.Append("<div class='meta'>");
        sb.Append($"Run ID: <strong>{HttpUtility.HtmlEncode(r.RunId)}</strong><br/>");
        sb.Append($"Model: <strong>{HttpUtility.HtmlEncode(r.ModelId)}</strong> &nbsp;|&nbsp; Judge: <strong>{HttpUtility.HtmlEncode(r.JudgeModelId)}</strong><br/>");
        sb.Append($"Dataset: <strong>{HttpUtility.HtmlEncode(Path.GetFileName(r.DatasetPath))}</strong> &nbsp;|&nbsp; Delta Threshold: <strong>{r.DeltaThreshold:F2}</strong> &nbsp;|&nbsp; Date: <strong>{r.Timestamp:yyyy-MM-dd HH:mm}</strong>");
        sb.Append("</div>");
        sb.Append($"<div class='pill' style='background:{accentColor};color:{pillFg};'>{r.OverallVerdict}</div>");
        sb.Append("</div>");

        // ── Stats grid ──
        sb.Append("<div class='stats'>");
        sb.Append($"<div class='stat'><div class='stat-val' style='color:#0d6efd;'>{totalCases}</div><div class='stat-lbl'>Cases Run</div></div>");
        sb.Append($"<div class='stat'><div class='stat-val' style='color:{(failGroups > 0 ? "#dc3545" : "#198754")};'>{failGroups}/{r.Groups.Count}</div><div class='stat-lbl'>Groups Failed</div></div>");
        sb.Append($"<div class='stat'><div class='stat-val' style='color:{(borderlineGroups > 0 ? "#fd7e14" : "#198754")};'>{borderlineGroups}</div><div class='stat-lbl'>Borderline Groups</div></div>");
        sb.Append($"<div class='stat'><div class='stat-val' style='color:{(avgMismatch >= 0.20 ? "#dc3545" : "#198754")};'>{avgMismatch:P0}</div><div class='stat-lbl'>Avg Mismatch Rate</div></div>");
        sb.Append("</div>");

        // ── Decision distribution (the officer) ──
        if (decisions.Any())
        {
            sb.Append("<div class='card'><h2>Decision Distribution — What the Model Said</h2>");
            sb.Append("<table><thead><tr><th>Decision</th><th>Count</th><th>Share</th><th></th></tr></thead><tbody>");
            foreach (var (dec, count) in decisions)
            {
                var pct = totalCases > 0 ? count * 100.0 / totalCases : 0;
                var bg = dec.ToLower() switch
                {
                    "approved" or "shortlisted" or "urgent" => "#198754",
                    "conditional" or "interview" or "standard" => "#ffc107",
                    _ => "#dc3545"
                };
                var fg = dec.ToLower() is "conditional" or "interview" or "standard" ? "#000" : "#fff";
                sb.Append($"<tr><td>{Badge(dec, bg, fg)}</td><td style='font-weight:700;'>{count}</td><td>{pct:F0}%</td>");
                sb.Append($"<td><div class='bar-wrap' style='width:200px;'><div class='bar' style='background:{bg};width:{pct:F0}%;'></div></div></td></tr>");
            }
            sb.Append("</tbody></table></div>");
        }

        // ── Group results table ──
        sb.Append("<div class='card'>");
        sb.Append($"<h2>Fairness by Group ({r.Groups.Count} groups tested)</h2>");
        sb.Append("<table><thead><tr><th>Group</th><th>Base Decision</th><th>Variant Decision</th><th>Mismatch Rate</th><th>Verdict</th><th>Judge Evidence</th></tr></thead><tbody>");
        foreach (var g in r.Groups)
        {
            var mismatchPct = g.TotalPairs > 0 ? $"{(int)Math.Round(g.Delta * 100)}%" : "—";
            var dBg = g.Delta >= 0.50 ? "#dc3545" : g.Delta >= 0.20 ? "#ffc107" : "#198754";
            var dFg = g.Delta >= 0.20 && g.Delta < 0.50 ? "#000" : "#fff";
            var vBg = g.Verdict == GroupVerdict.PASS ? "#198754" : g.Verdict == GroupVerdict.BORDERLINE ? "#ffc107" : "#dc3545";
            var vFg = g.Verdict == GroupVerdict.BORDERLINE ? "#000" : "#fff";
            var baseBg = DecisionBg(g.BaseDecision); var baseFg = DecisionFg(g.BaseDecision);
            var varBg = DecisionBg(g.VariantDecision); var varFg = DecisionFg(g.VariantDecision);
            sb.Append($"<tr><td style='font-weight:600;'>{HttpUtility.HtmlEncode(g.Group)}</td>");
            sb.Append($"<td>{(string.IsNullOrEmpty(g.BaseDecision) ? "—" : Badge(g.BaseDecision, baseBg, baseFg))}</td>");
            sb.Append($"<td>{(string.IsNullOrEmpty(g.VariantDecision) ? "—" : Badge(g.VariantDecision, varBg, varFg))}</td>");
            sb.Append($"<td>{Badge(mismatchPct, dBg, dFg)}</td>");
            sb.Append($"<td>{Badge(g.Verdict.ToString(), vBg, vFg)}</td>");
            sb.Append($"<td style='font-size:0.82rem;color:#6c757d;'>{HttpUtility.HtmlEncode(g.Evidence ?? "")}</td></tr>");
        }
        sb.Append("</tbody></table></div>");

        // ── Top 3 biased examples ──
        var top3ByMismatch = r.Groups
            .Where(g => g.Verdict == GroupVerdict.FAIL || g.Verdict == GroupVerdict.BORDERLINE)
            .OrderByDescending(g => g.Delta)
            .Take(3)
            .ToList();

        if (top3ByMismatch.Any())
        {
            sb.Append("<div class='card'><h2>Top Biased Groups — Decision Changes Detected</h2>");
            sb.Append("<p style='color:#6c757d;font-size:0.88rem;margin-bottom:16px;'>Groups where the model gave different decisions to demographically varied applicants with identical data.</p>");
            int n = 1;
            foreach (var g in top3ByMismatch)
            {
                var headerBg = g.Verdict == GroupVerdict.FAIL ? "#dc3545" : "#ffc107";
                var headerFg = g.Verdict == GroupVerdict.FAIL ? "#fff" : "#000";
                var baseBg = DecisionBg(g.BaseDecision); var baseFg = DecisionFg(g.BaseDecision);
                var varBg = DecisionBg(g.VariantDecision); var varFg = DecisionFg(g.VariantDecision);
                var mismatchPct = g.TotalPairs > 0 ? $"{(int)Math.Round(g.Delta * 100)}%" : "?";
                sb.Append($"<div class='example-block' style='border:1px solid #dee2e6;border-radius:8px;margin-bottom:16px;overflow:hidden;'>");
                sb.Append($"<div style='background:{headerBg};color:{headerFg};padding:10px 16px;display:flex;justify-content:space-between;align-items:center;'>");
                sb.Append($"<span style='font-weight:700;font-size:0.95rem;'>Example #{n} &mdash; {HttpUtility.HtmlEncode(g.Group)}</span>");
                sb.Append($"<span style='font-size:0.85rem;'>Mismatch Rate: <strong>{mismatchPct}</strong> &nbsp;|&nbsp; {g.DecisionChangedCount}/{g.TotalPairs} runs &nbsp;|&nbsp; {Badge(g.BaseDecision, baseBg, baseFg)} &rarr; {Badge(g.VariantDecision, varBg, varFg)}</span>");
                sb.Append("</div>");
                var baseEx = raw.FirstOrDefault(x => x.Group == g.Group && x.Variant == "base");
                var variantEx = raw.FirstOrDefault(x => x.Group == g.Group && x.Variant != "base"
                    && !string.IsNullOrEmpty(x.Decision)
                    && !string.Equals(x.Decision, baseEx?.Decision, StringComparison.OrdinalIgnoreCase));

                sb.Append("<div style='padding:14px 16px;'>");

                if (baseEx != null && variantEx != null)
                {
                    sb.Append("<div style='display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;'>");

                    sb.Append("<div>");
                    sb.Append("<div style='font-size:0.7rem;text-transform:uppercase;font-weight:700;color:#6c757d;margin-bottom:4px;'>Base Response</div>");
                    sb.Append($"<div style='background:#f8f9fa;border-radius:4px;padding:10px;font-family:monospace;font-size:0.82rem;white-space:pre-wrap;'>{HttpUtility.HtmlEncode(baseEx.ActualOutput ?? baseEx.Prompt)}</div>");
                    sb.Append("</div>");

                    sb.Append("<div>");
                    sb.Append($"<div style='font-size:0.7rem;text-transform:uppercase;font-weight:700;color:#6c757d;margin-bottom:4px;'>Variant Response ({HttpUtility.HtmlEncode(variantEx.Variant ?? "")})</div>");
                    sb.Append($"<div style='background:#f8f9fa;border-radius:4px;padding:10px;font-family:monospace;font-size:0.82rem;white-space:pre-wrap;'>{HttpUtility.HtmlEncode(variantEx.ActualOutput ?? variantEx.Prompt)}</div>");
                    sb.Append("</div>");

                    sb.Append("</div>");
                }

                if (!string.IsNullOrWhiteSpace(g.Evidence))
                {
                    sb.Append("<div>");
                    sb.Append("<div style='font-size:0.7rem;text-transform:uppercase;font-weight:700;color:#6c757d;margin-bottom:4px;'>Judge Explanation</div>");
                    sb.Append($"<div style='background:#fff3cd;border-radius:4px;padding:10px;font-size:0.85rem;color:#664d03;'>{HttpUtility.HtmlEncode(g.Evidence)}</div>");
                    sb.Append("</div>");
                }

                sb.Append("</div></div>");
                n++;
            }
            sb.Append("</div>");
        }

        return Doc($"AGILE Bias Audit — {r.RunId[..8]}", accentColor, sb.ToString());
    }

    // ── QuickAudit CSV ───────────────────────────────────────────────────────

    public static byte[] ExportQuickAuditCsv(List<QuickAuditDimensionResult> results)
    {
        var sb = new StringBuilder();
        sb.AppendLine("Dimension,BiasScore,Status,TestCaseCount");
        foreach (var r in results.OrderByDescending(x => x.BiasScore))
            sb.AppendLine($"{r.Dimension},{r.BiasScore:F4},{r.Status},{r.TestCaseCount}");
        return Encoding.UTF8.GetBytes(sb.ToString());
    }

    // ── ComparisonReport ──────────────────────────────────────────────────────

    public static string GenerateComparisonReport(ComparisonReport r)
    {
        var allApplicants = r.Reports
            .SelectMany(m => m.Results.Select(x => x.TestCaseId.Split("_Run")[0]))
            .Distinct().OrderBy(x => x).ToList();

        var sb = new StringBuilder();

        // Header
        sb.Append("<div class='header'>");
        sb.Append("<h1>AGILE Model Comparison Report</h1>");
        sb.Append("<div class='meta'>");
        sb.Append($"Models: <strong>{string.Join(" vs ", r.Reports.Select(m => HttpUtility.HtmlEncode(m.ModelId)))}</strong> &nbsp;|&nbsp; ");
        sb.Append($"Date: <strong>{r.CreatedAt:yyyy-MM-dd HH:mm}</strong>");
        sb.Append("</div>");
        sb.Append($"<div class='pill' style='background:#198754;'>&#127942; Least Biased: {HttpUtility.HtmlEncode(r.Winner)} &mdash; Avg Bias {r.WinnerBias:F1}</div>");
        sb.Append("</div>");

        // Summary row
        sb.Append($"<div style='display:grid;grid-template-columns:repeat({r.Reports.Count},1fr);gap:12px;margin-bottom:20px;'>");
        foreach (var m in r.Reports.OrderBy(m => m.AverageBiasScore))
        {
            var isWinner = m.ModelId == r.Winner;
            var cardBg = isWinner ? "#d1e7dd" : "#fff";
            sb.Append($"<div style='background:{cardBg};border:1px solid #dee2e6;border-radius:8px;padding:16px;text-align:center;'>");
            sb.Append($"<div style='font-size:0.75rem;text-transform:uppercase;color:#6c757d;'>{HttpUtility.HtmlEncode(m.ModelId)}</div>");
            sb.Append($"<div style='font-size:1.8rem;font-weight:700;color:{(isWinner ? "#198754" : "#495057")};'>{m.AverageBiasScore:F1}</div>");
            sb.Append("<div style='font-size:0.8rem;color:#6c757d;'>avg bias score</div>");
            if (isWinner) sb.Append("<div style='margin-top:6px;font-weight:700;color:#198754;'>LEAST BIASED</div>");
            sb.Append("</div>");
        }
        sb.Append("</div>");

        // Table
        sb.Append("<div class='card'><h2>Per-Applicant Bias Scores by Model</h2>");
        sb.Append("<table><thead><tr><th>Applicant ID</th>");
        foreach (var m in r.Reports)
        {
            var winnerStyle = m.ModelId == r.Winner ? "background:#d1e7dd;" : "";
            sb.Append($"<th style='{winnerStyle}'>{HttpUtility.HtmlEncode(m.ModelId)}{(m.ModelId == r.Winner ? " &#127942;" : "")}</th>");
        }
        sb.Append("</tr></thead><tbody>");
        foreach (var applicantId in allApplicants)
        {
            sb.Append($"<tr><td style='font-weight:600;font-family:monospace;'>{HttpUtility.HtmlEncode(applicantId)}</td>");
            foreach (var m in r.Reports)
            {
                var grp = m.Results.Where(x => x.TestCaseId.Split("_Run")[0] == applicantId).ToList();
                if (!grp.Any()) { sb.Append("<td style='color:#adb5bd;'>-</td>"); continue; }
                var bias = grp.Average(x => x.BiasScore);
                var cellBg = bias > 6 ? "#f8d7da" : bias > 3 ? "#fff3cd" : "#d1e7dd";
                var cellFg = bias > 6 ? "#842029" : bias > 3 ? "#664d03" : "#0f5132";
                sb.Append($"<td style='background:{cellBg};color:{cellFg};font-weight:600;'>{bias:F1}</td>");
            }
            sb.Append("</tr>");
        }
        sb.Append("</tbody></table></div>");

        return Doc($"AGILE Comparison — {r.ComparisonId[..8]}", "#0d6efd", sb.ToString());
    }
}
