using System.Text;
using System.Web;
using Agile.Core.Models;

namespace Agile.Web.Services;

public static class ReportHtmlExporter
{
    private const string BaseStyle = @"
*{box-sizing:border-box;}
body{font-family:'Segoe UI',system-ui,sans-serif;margin:0;padding:24px;background:#f8f9fa;color:#212529;}
.header{background:#fff;border-radius:8px;padding:24px;margin-bottom:20px;box-shadow:0 1px 4px rgba(0,0,0,0.08);}
h1{margin:0 0 6px;font-size:1.5rem;color:#0d6efd;}
.meta{color:#6c757d;font-size:0.9rem;line-height:1.8;}
.card{background:#fff;border-radius:8px;padding:20px;margin-bottom:20px;box-shadow:0 1px 4px rgba(0,0,0,0.08);}
h2{font-size:1.1rem;margin:0 0 14px;color:#495057;border-bottom:1px solid #dee2e6;padding-bottom:8px;}
table{width:100%;border-collapse:collapse;font-size:0.9rem;}
th{background:#f8f9fa;padding:8px 12px;text-align:left;font-weight:600;border-bottom:2px solid #dee2e6;}
td{padding:8px 12px;border-bottom:1px solid #f0f0f0;vertical-align:middle;}
tr:hover{background:#f8f9fa;}
.badge{padding:2px 10px;border-radius:12px;font-size:0.75rem;font-weight:600;color:#fff;display:inline-block;}
.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:20px;}
.stat{background:#fff;border-radius:8px;padding:16px;box-shadow:0 1px 4px rgba(0,0,0,0.08);text-align:center;}
.stat-val{font-size:1.6rem;font-weight:700;}
.stat-lbl{font-size:0.75rem;text-transform:uppercase;color:#6c757d;letter-spacing:.5px;}
.footer{text-align:center;color:#adb5bd;font-size:0.8rem;margin-top:30px;}
.pill{display:inline-block;padding:6px 18px;border-radius:20px;font-weight:700;font-size:1rem;color:#fff;margin-top:10px;}
.bar-wrap{background:#e9ecef;border-radius:4px;height:12px;width:120px;display:inline-block;}
.bar{height:100%;border-radius:4px;}";

    private static string Doc(string title, string accentColor, string body) =>
        $"<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'/><title>{HttpUtility.HtmlEncode(title)}</title>" +
        $"<style>{BaseStyle}.header{{border-left:6px solid {accentColor};}}</style></head><body>{body}" +
        $"<div class='footer'>Generated by AGILE Platform &middot; {DateTime.Now:yyyy-MM-dd HH:mm} &middot; AI Governance, Integration &amp; Lifecycle Evaluation</div></body></html>";

    private static string Badge(string text, string bg, string fg = "#fff") =>
        $"<span class='badge' style='background:{bg};color:{fg};'>{HttpUtility.HtmlEncode(text)}</span>";

    private static (string bg, string fg) BiasColor(double bias) =>
        bias > 6 ? ("#dc3545", "#fff") : bias > 3 ? ("#ffc107", "#000") : ("#198754", "#fff");

    // ── RunReport ────────────────────────────────────────────────────────────

    public static string GenerateRunReport(RunReport r)
    {
        var passRate = r.TotalTests > 0 ? (r.Passed * 100.0 / r.TotalTests) : 0;
        var avgBias = r.Results.Count > 0 ? r.Results.Average(x => x.BiasScore) : 0;
        var verdict = r.Failed > 0 ? "BIASED" : "CONSISTENT";
        var verdictBg = r.Failed > 0 ? "#dc3545" : "#198754";

        var sb = new StringBuilder();

        // Header
        sb.Append("<div class='header'>");
        sb.Append("<h1>AGILE Bias Audit Report</h1>");
        sb.Append("<div class='meta'>");
        sb.Append($"Run ID: <strong>{HttpUtility.HtmlEncode(r.RunId)}</strong> &nbsp;|&nbsp; ");
        sb.Append($"Model: <strong>{HttpUtility.HtmlEncode(r.ModelId)}</strong> &nbsp;|&nbsp; ");
        sb.Append($"Dataset: <strong>{HttpUtility.HtmlEncode(Path.GetFileName(r.DatasetPath))}</strong> &nbsp;|&nbsp; ");
        sb.Append($"Date: <strong>{r.CreatedAt:yyyy-MM-dd HH:mm}</strong>");
        sb.Append("</div>");
        sb.Append($"<div class='pill' style='background:{verdictBg};'>{verdict}</div>");
        sb.Append("</div>");

        // Stats
        sb.Append("<div class='stats'>");
        sb.Append($"<div class='stat'><div class='stat-val' style='color:#0d6efd;'>{r.TotalTests}</div><div class='stat-lbl'>Total Cases</div></div>");
        sb.Append($"<div class='stat'><div class='stat-val' style='color:#198754;'>{passRate:F1}%</div><div class='stat-lbl'>Pass Rate</div></div>");
        sb.Append($"<div class='stat'><div class='stat-val' style='color:#dc3545;'>{avgBias:F2}</div><div class='stat-lbl'>Avg Bias Score</div></div>");
        sb.Append($"<div class='stat'><div class='stat-val' style='color:{verdictBg};'>{r.Failed}</div><div class='stat-lbl'>Failed Cases</div></div>");
        sb.Append("</div>");

        // Groups
        sb.Append("<div class='card'><h2>Bias by Dimension</h2>");
        sb.Append("<table><thead><tr><th>Dimension</th><th>Bias Level</th><th>Avg Score</th><th>Pass Rate</th><th>Risk</th></tr></thead><tbody>");
        foreach (var g in r.Results.GroupBy(x => x.TestCaseId.Split("_Run")[0])
            .Select(g => new { Group = g.Key, Bias = g.Average(x => x.BiasScore), PassPct = g.Count(x => x.Passed) * 100.0 / g.Count() })
            .OrderByDescending(g => g.Bias))
        {
            var (bg, fg) = BiasColor(g.Bias);
            var riskText = g.Bias > 6 ? "HIGH RISK" : g.Bias > 3 ? "MODERATE" : "LOW RISK";
            var barPct = (int)Math.Min(g.Bias / 10.0 * 100, 100);
            sb.Append($"<tr><td style='font-weight:600;'>{HttpUtility.HtmlEncode(g.Group)}</td>");
            sb.Append($"<td><div class='bar-wrap'><div class='bar' style='background:{bg};width:{barPct}%;'></div></div></td>");
            sb.Append($"<td style='font-weight:700;'>{g.Bias:F1}</td>");
            sb.Append($"<td>{g.PassPct:F0}%</td>");
            sb.Append($"<td>{Badge(riskText, bg, fg)}</td></tr>");
        }
        sb.Append("</tbody></table></div>");

        // Cases
        sb.Append($"<div class='card'><h2>All Test Cases ({r.Results.Count})</h2>");
        sb.Append("<table><thead><tr><th>Case ID</th><th>Prompt</th><th>Bias Score</th><th>Verdict</th></tr></thead><tbody>");
        foreach (var res in r.Results)
        {
            var (bg, fg) = BiasColor(res.BiasScore);
            var truncated = res.Prompt.Length > 90 ? res.Prompt[..90] + "…" : res.Prompt;
            sb.Append($"<tr><td style='font-family:monospace;font-size:0.8rem;color:#6c757d;'>{HttpUtility.HtmlEncode(res.TestCaseId)}</td>");
            sb.Append($"<td style='max-width:300px;font-size:0.85rem;' title='{HttpUtility.HtmlEncode(res.Prompt)}'>{HttpUtility.HtmlEncode(truncated)}</td>");
            sb.Append($"<td>{Badge(res.BiasScore.ToString("F1"), bg, fg)}</td>");
            sb.Append($"<td>{Badge(res.Passed ? "PASS" : "FAIL", res.Passed ? "#198754" : "#dc3545")}</td></tr>");
        }
        sb.Append("</tbody></table></div>");

        return Doc($"AGILE Report — {r.RunId[..8]}", "#0d6efd", sb.ToString());
    }

    // ── BiasVerdictReport ─────────────────────────────────────────────────────

    public static string GenerateBiasVerdictReport(BiasVerdictReport r)
    {
        var accentColor = r.OverallVerdict == OverallVerdict.COMPLIANT ? "#198754"
            : r.OverallVerdict == OverallVerdict.REVIEW_REQUIRED ? "#ffc107" : "#dc3545";
        var pillFg = r.OverallVerdict == OverallVerdict.REVIEW_REQUIRED ? "#000" : "#fff";

        var sb = new StringBuilder();

        sb.Append("<div class='header'>");
        sb.Append("<h1>AGILE Counterfactual Bias Audit</h1>");
        sb.Append("<div class='meta'>");
        sb.Append($"Run ID: <strong>{HttpUtility.HtmlEncode(r.RunId)}</strong><br/>");
        sb.Append($"Model: <strong>{HttpUtility.HtmlEncode(r.ModelId)}</strong> &nbsp;|&nbsp; Judge: <strong>{HttpUtility.HtmlEncode(r.JudgeModelId)}</strong><br/>");
        sb.Append($"Dataset: <strong>{HttpUtility.HtmlEncode(Path.GetFileName(r.DatasetPath))}</strong> &nbsp;|&nbsp; Delta Threshold: <strong>{r.DeltaThreshold:F2}</strong> &nbsp;|&nbsp; Date: <strong>{r.Timestamp:yyyy-MM-dd HH:mm}</strong>");
        sb.Append("</div>");
        sb.Append($"<div class='pill' style='background:{accentColor};color:{pillFg};'>{r.OverallVerdict}</div>");
        sb.Append("</div>");

        sb.Append("<div class='card'>");
        sb.Append($"<h2>Results by Bias Dimension ({r.Groups.Count} groups)</h2>");
        sb.Append("<table><thead><tr><th>Group</th><th>Base Score</th><th>Variant Score</th><th>Delta</th><th>Verdict</th><th>Evidence</th></tr></thead><tbody>");
        foreach (var g in r.Groups)
        {
            var dBg = g.Delta >= 0.10 ? "#dc3545" : g.Delta >= 0.05 ? "#ffc107" : "#198754";
            var dFg = g.Delta >= 0.05 && g.Delta < 0.10 ? "#000" : "#fff";
            var vBg = g.Verdict == GroupVerdict.PASS ? "#198754" : g.Verdict == GroupVerdict.BORDERLINE ? "#ffc107" : "#dc3545";
            var vFg = g.Verdict == GroupVerdict.BORDERLINE ? "#000" : "#fff";
            sb.Append($"<tr><td style='font-weight:600;'>{HttpUtility.HtmlEncode(g.Group)}</td>");
            sb.Append($"<td>{g.BaseScore:F3}</td><td>{g.VariantScore:F3}</td>");
            sb.Append($"<td>{Badge(g.Delta.ToString("F3"), dBg, dFg)}</td>");
            sb.Append($"<td>{Badge(g.Verdict.ToString(), vBg, vFg)}</td>");
            sb.Append($"<td style='font-size:0.82rem;color:#6c757d;'>{HttpUtility.HtmlEncode(g.Evidence ?? "")}</td></tr>");
        }
        sb.Append("</tbody></table></div>");

        return Doc($"AGILE Bias Audit — {r.RunId[..8]}", accentColor, sb.ToString());
    }

    // ── ComparisonReport ──────────────────────────────────────────────────────

    public static string GenerateComparisonReport(ComparisonReport r)
    {
        var allApplicants = r.Reports
            .SelectMany(m => m.Results.Select(x => x.TestCaseId.Split("_Run")[0]))
            .Distinct().OrderBy(x => x).ToList();

        var sb = new StringBuilder();

        // Header
        sb.Append("<div class='header'>");
        sb.Append("<h1>AGILE Model Comparison Report</h1>");
        sb.Append("<div class='meta'>");
        sb.Append($"Models: <strong>{string.Join(" vs ", r.Reports.Select(m => HttpUtility.HtmlEncode(m.ModelId)))}</strong> &nbsp;|&nbsp; ");
        sb.Append($"Date: <strong>{r.CreatedAt:yyyy-MM-dd HH:mm}</strong>");
        sb.Append("</div>");
        sb.Append($"<div class='pill' style='background:#198754;'>&#127942; Least Biased: {HttpUtility.HtmlEncode(r.Winner)} &mdash; Avg Bias {r.WinnerBias:F1}</div>");
        sb.Append("</div>");

        // Summary row
        sb.Append($"<div style='display:grid;grid-template-columns:repeat({r.Reports.Count},1fr);gap:12px;margin-bottom:20px;'>");
        foreach (var m in r.Reports.OrderBy(m => m.AverageBiasScore))
        {
            var isWinner = m.ModelId == r.Winner;
            var cardBg = isWinner ? "#d1e7dd" : "#fff";
            sb.Append($"<div style='background:{cardBg};border:1px solid #dee2e6;border-radius:8px;padding:16px;text-align:center;'>");
            sb.Append($"<div style='font-size:0.75rem;text-transform:uppercase;color:#6c757d;'>{HttpUtility.HtmlEncode(m.ModelId)}</div>");
            sb.Append($"<div style='font-size:1.8rem;font-weight:700;color:{(isWinner ? "#198754" : "#495057")};'>{m.AverageBiasScore:F1}</div>");
            sb.Append("<div style='font-size:0.8rem;color:#6c757d;'>avg bias score</div>");
            if (isWinner) sb.Append("<div style='margin-top:6px;font-weight:700;color:#198754;'>LEAST BIASED</div>");
            sb.Append("</div>");
        }
        sb.Append("</div>");

        // Table
        sb.Append("<div class='card'><h2>Per-Applicant Bias Scores by Model</h2>");
        sb.Append("<table><thead><tr><th>Applicant ID</th>");
        foreach (var m in r.Reports)
        {
            var winnerStyle = m.ModelId == r.Winner ? "background:#d1e7dd;" : "";
            sb.Append($"<th style='{winnerStyle}'>{HttpUtility.HtmlEncode(m.ModelId)}{(m.ModelId == r.Winner ? " &#127942;" : "")}</th>");
        }
        sb.Append("</tr></thead><tbody>");
        foreach (var applicantId in allApplicants)
        {
            sb.Append($"<tr><td style='font-weight:600;font-family:monospace;'>{HttpUtility.HtmlEncode(applicantId)}</td>");
            foreach (var m in r.Reports)
            {
                var grp = m.Results.Where(x => x.TestCaseId.Split("_Run")[0] == applicantId).ToList();
                if (!grp.Any()) { sb.Append("<td style='color:#adb5bd;'>-</td>"); continue; }
                var bias = grp.Average(x => x.BiasScore);
                var cellBg = bias > 6 ? "#f8d7da" : bias > 3 ? "#fff3cd" : "#d1e7dd";
                var cellFg = bias > 6 ? "#842029" : bias > 3 ? "#664d03" : "#0f5132";
                sb.Append($"<td style='background:{cellBg};color:{cellFg};font-weight:600;'>{bias:F1}</td>");
            }
            sb.Append("</tr>");
        }
        sb.Append("</tbody></table></div>");

        return Doc($"AGILE Comparison — {r.ComparisonId[..8]}", "#0d6efd", sb.ToString());
    }
}
